# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    - name: Install dependencies
      run: |
        go get github.com/BurntSushi/toml
        go get github.com/gdamore/tcell/v2
        go get github.com/ncruces/zenity
        go get github.com/rivo/tview

    - name: Build
      run: GOOS=windows GOARCH=amd64 go build -v ./...

    - name: Test
      run: GOOS=windows GOARCH=amd64 go test -v ./...
